export const screens = {
	SEARCH_NAVIGATION: "SEARCH_NAVIGATION",
	SEARCH: "SEARCH",
	ADDRESS_MODAL: "ADDRESS_MODAL",
	SEARCH_RESULT_NAVIGATION: "SEARCH_RESULT_NAVIGATION",
	SEARCH_LOADING: "SEARCH_LOADING",
	SEARCH_RESULTS: "SEARCH_RESULTS",
	REPORTS_NAVIGATION: "REPORTS_NAVIGATION",
	REPORTS: "REPORTS",
	REPORT: "REPORT",
	PREFERENCES: "PREFERENCES",
};
