export const screens = {
	SEARCH_NAVIGATION: "SEARCH_NAVIGATION",
	SEARCH: "SEARCH",
	SEARCH_RESULT_NAVIGATION: "SEARCH_RESULT_NAVIGATION",
	SEARCH_LOADING: "SEARCH_LOADING",
	SEARCH_RESULTS: "SEARCH_RESULTS",
	REPORTS: "REPORTS",
	PREFERENCES: "PREFERENCES",
};
